#:schema node_modules/wrangler/config-schema.json
name = "ai"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[vectorize]]
binding = "NOTES_INDEX_2"
index_name = "notes-index-1024-2"

[[durable_objects.bindings]]
name = "INDEX_METADATA"
class_name = "IndexMetadata"

[[migrations]]
tag = "v1"
new_classes = ["IndexMetadata"]
